from pathlib import Path
import shutil,json
p=Path(__file__).resolve().parent
(p/'slides/assets').mkdir(parents=True,exist_ok=True)
src=p.parent/'visual-preview/slides/assets'
shutil.copytree(src/'fonts',p/'slides/assets/fonts',dirs_exist_ok=True)
shutil.copy(src/'gsap.min.js',p/'slides/assets/gsap.min.js')
# Corrected generated asset is retained in slides/assets/dock.png
(p/'content.json').write_text(json.dumps({'slides':[{'type':'cover'}]}))
html='''<!doctype html><html><head><meta charset="utf-8"><style>
@font-face{font-family:Poppins;src:url(assets/fonts/Poppins-Bold.ttf);font-weight:700}@font-face{font-family:Poppins;src:url(assets/fonts/Poppins-Regular.ttf);font-weight:400}@font-face{font-family:Preahvihear;src:url(assets/fonts/Preahvihear-Regular.ttf)}
*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1350px;overflow:hidden}#scene{position:relative;width:1080px;height:1350px;background:#03161b;color:white}.photo{position:absolute;width:1080px;height:1350px;object-fit:cover}.shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(3,22,27,.25),transparent 62%,rgba(3,22,27,.25))}.tx{position:absolute;z-index:3}.hook{left:68px;top:62px;font:700 100px/1.03 Poppins;letter-spacing:-3px;width:950px}.hook span{color:#36c2d4}.question{left:72px;top:448px;width:810px;font:36px/1.43 Preahvihear}.sub{left:72px;top:1185px;width:900px;font:400 29px/1.4 Poppins}.sub b{color:#36c2d4}.footer{position:absolute;left:72px;bottom:36px;font:26px Poppins}.count{position:absolute;right:72px;bottom:36px;font:26px Poppins}.clock{position:absolute;left:925px;top:416px;width:122px;height:122px;border-radius:50%;background:radial-gradient(circle,#17333b,#071c21);border:6px solid #647b7d;box-shadow:0 5px 14px #0009}.clock svg{width:110px;height:110px}.hand{transform-origin:60px 60px}.rim{fill:none;stroke:#ffaa40;stroke-width:4;opacity:0}.halo{position:absolute;inset:-15px;border:2px solid #ffaa40;border-radius:50%;opacity:0}
</style></head><body><div id="scene" data-composition-id="dock-cover" data-width="1080" data-height="1350" data-duration="4"><img class="photo" src="assets/dock.png"><div class="shade"></div><div class="tx hook">CATCH<br><span>DELIVERY DELAYS</span><br><span style="font-size:57px;letter-spacing:-1px;color:white">before your customer does.</span></div><div class="tx question">Your team already handles the unexpected.<br>What if you heard first?</div><div class="clock"><div class="halo"></div><svg viewBox="0 0 120 120"><circle class="rim" cx="60" cy="60" r="54"/><g stroke="#b4c8cb" stroke-width="2">TICKS</g><line x1="60" y1="60" x2="38" y2="44" stroke="#dce8e9" stroke-width="4" stroke-linecap="round"/><line class="hand" x1="60" y1="60" x2="60" y2="18" stroke="#36c2d4" stroke-width="3" stroke-linecap="round"/><circle cx="60" cy="60" r="4" fill="#e0eff0"/></svg></div><div class="tx sub">Delays start small. <b>Swipe to see where.</b> →</div><div class="footer">@arealtimetech</div><div class="count">01/09</div></div><script src="assets/gsap.min.js"></script><script>
const hand=document.querySelector('.hand'),rim=document.querySelector('.rim'),halo=document.querySelector('.halo');function R(t){const u=Math.min(1,Math.max(0,(t-.35)/1.5));hand.style.transform=`rotate(${u*70}deg)`;const f=Math.min(1,Math.max(0,(t-1.65)/.25));rim.style.opacity=f;hand.style.stroke=t>1.65?'#ffaa40':'#36c2d4';const a=(t-1.7)/.8;halo.style.opacity=a>0&&a<1?Math.sin(a*Math.PI)*.5:0;halo.style.transform=`scale(${1+Math.max(0,Math.min(1,a))*.25})`;}const st={t:0};const tl=gsap.timeline({paused:true});tl.to(st,{t:4,duration:4,ease:'none',onUpdate:()=>R(st.t)},0);window.__timelines={'dock-cover':tl};R(0);
</script></body></html>'''
import math
lines=''.join(f'<line x1="{60+46*math.sin(i*math.pi/6):.2f}" y1="{60-46*math.cos(i*math.pi/6):.2f}" x2="{60+50*math.sin(i*math.pi/6):.2f}" y2="{60-50*math.cos(i*math.pi/6):.2f}"/>' for i in range(12))
(p/'slides/slide-01.html').write_text(html.replace('TICKS',lines))
(p/'README.md').write_text('# Corrected loading-bay cover preview\n\nTruck rear faces dock, cab faces outward; disconnected conveyor removed. Closed dock shutter and waiting pallet show blocked pickup. Clock advances once, turns amber and holds; no floating or siren. Exact supplied cover copy, local Poppins and Preahvihear fonts. 4-second motion preview for review; other slides pending.\n')
